# Android Gradle Properties
android.useAndroidX=true
android.enableJetifier=true

# Gradle Performance Optimizations
org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Enable R8 full mode
android.enableR8.fullMode=true

# Kotlin
kotlin.code.style=official
